name: flutter_iap_validator
description: A Flutter package for secure in-app purchase and receipt validation, supporting subscriptions and consumables with Firebase Functions or a custom Dart backend.
version: 1.0.0
homepage: https://github.com/Destiny-Ed/flutter_iap_validator

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.5.3
  http: ^1.4.0
  in_app_purchase: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.flutter_iap_validator
        pluginClass: FlutterIapValidatorPlugin
      ios:
        pluginClass: FlutterIapValidatorPlugin
