name: iap_validator_server

description: A Dart server for validating in-app purchase receipts with Firebase Auth.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  shelf: ^1.4.0
  http: ^1.2.2
  firebase_admin: ^0.3.0+1
  googleapis_auth: ^1.4.1

dev_dependencies:
  test: ^1.24.0